// Generates src/index.ts from the contract ABIs exported by Foundry (contracts/abi/*.json).
// Never hand-edit src/index.ts (CLAUDE.md section 2). Run after any contract change:
//   (cd contracts && for c in Escrow EscrowFactory IEscrow IEscrowFactory; do forge inspect $c abi --json > abi/$c.json; done)
//   pnpm --filter @chain/abi generate
// `--check` fails if the committed file is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../../../contracts/abi/", import.meta.url));
const out = fileURLToPath(new URL("../src/index.ts", import.meta.url));
const contracts = [
  ["escrowAbi", "Escrow"],
  ["escrowFactoryAbi", "EscrowFactory"],
];

let src = "// GENERATED by scripts/generate.mjs from contracts/abi/*.json. Do not edit.\n\n";
for (const [name, file] of contracts) {
  const abi = JSON.parse(readFileSync(`${root}${file}.json`, "utf8"));
  src += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}

if (process.argv.includes("--check")) {
  const current = readFileSync(out, "utf8");
  if (current !== src) {
    console.error("@chain/abi is stale: run `pnpm --filter @chain/abi generate`");
    process.exit(1);
  }
  console.log("@chain/abi up to date");
} else {
  writeFileSync(out, src);
  console.log(`wrote ${out}`);
}
